[package]
name = "wifi-densepose-api"
version.workspace = true
edition.workspace = true
description = "REST API for WiFi-DensePose"
license.workspace = true
authors = ["Joonho Choi <cc@exe.blue>"]
repository.workspace = true
documentation.workspace = true
keywords = ["wifi", "api", "rest", "densepose", "websocket"]
categories = ["web-programming::http-server", "science"]
readme = "README.md"

[package.metadata.revaid.origin]
id = "REVAID.ORIGIN"
name = "Joonho Choi"
email = "cc@exe.blue"
phone = "+821071046821"
link = "https://orcid.org/0009-0006-7585-8185"
endpoint = "MURON"
middleware = "REVAID.LINK"


[dependencies]
